Proxy process.on("exit") to avoid MaxListenersExceededWarning
mike-marcacci/fs-capacitor pull request #42
Opened 2021-04-12 03:09 UTC by mike-marcacci

This fixes #30, working around node's MaxListenersExceededWarning by creating a "proxy" event emitter to forward `exit` events.

This is a more concise alternative to #34.

2021-04-13 20:01 UTC, gabegorelick commented
@mike-marcacci Won't you now just get the MaxListenersExceededWarning on the `processExitProxy` object instead of on `process`? That's somewhat better since you can call `setMaxListeners(Infinity)` on this proxy object, but I don't see that in this PR.

2021-04-14 02:47 UTC, mike-marcacci commented
@gabegorelick 🤦🏼 indeed haha; that is now fixed in the PR.

2021-04-14 03:09 UTC, jaydenseric requested changes

2021-04-14 03:09 UTC, jaydenseric commented on src/index.ts
> +// https://github.com/mike-marcacci/fs-capacitor/issues/30
```suggestion
// Use a “proxy” event emitter configured to have an infinite maximum number of
// listeners to prevent Node.js max listeners exceeded warnings if many
// `fs-capacitor` `ReadStream` instances are created at the same time. See:
// https://github.com/mike-marcacci/fs-capacitor/issues/30
```

2021-04-14 03:09 UTC, jaydenseric commented on src/index.ts
> +process.addListener("exit", () => processExitProxy.emit("exit"));
```suggestion
process.once("exit", () => processExitProxy.emit("exit"));
```

https://nodejs.org/dist/latest-v15.x/docs/api/events.html#events_emitter_once_eventname_listener

2021-04-14 03:09 UTC, jaydenseric commented on src/index.ts
> +        processExitProxy.addListener("exit", this._cleanupSync);
```suggestion
        processExitProxy.once("exit", this._cleanupSync);
```

2021-04-14 03:09 UTC, jaydenseric commented on src/index.ts
> +    processExitProxy.removeListener("exit", this._cleanupSync);
```suggestion
    processExitProxy.off("exit", this._cleanupSync);
```

https://nodejs.org/dist/latest-v15.x/docs/api/events.html#events_emitter_off_eventname_listener

2021-04-14 03:09 UTC, jaydenseric commented on src/index.ts
> +        processExitProxy.removeListener("exit", this._cleanupSync);
```suggestion
        processExitProxy.off("exit", this._cleanupSync);
```

2021-04-14 03:13 UTC, jaydenseric commented
@mike-marcacci may I suggest doing regular commits when working on the PR, vs force-pushes? That way the email notifications, PR history, etc. has the changes as incremental diffs which is easier to follow. You can always squash the PR to a single commit when merging it if you prefer a single commit on `master` afterwards.

2021-04-14 03:16 UTC, mike-marcacci commented on src/index.ts
> +process.addListener("exit", () => processExitProxy.emit("exit"));
Ah yes, haha. I suppose in this case `once` and `on`/`addListener` are actually comparable (since `exit` is by definition a singleton event).

2021-04-14 03:22 UTC, mike-marcacci commented
@jaydenseric yes indeed, that would probably be helpful here. I'm in the habit of staging larger PRs with distinct, logical commits (as opposed to "historical" commits), which can then be reviewed more easily. But for smaller PRs, yes I definitely agree: keeping the history greatly helps collaboration 👍🏼

2021-04-14 03:58 UTC, jaydenseric commented on src/index.ts
> +    readStream.on("close", remove);
Is this better being `.once`, and if it was, would that make the manual `.off` later unnecessary?

2021-04-14 04:13 UTC, mike-marcacci commented on src/index.ts
> +    readStream.on("close", remove);
Excellent observation, yes. Originally, when supporting node 8, we could not use `on` `off` and `once` methods on streams (because they did not exist). Accordingly, I chose to use `addListener` and `removeListener` both on streams and events, for consistency. With support for that version long-gone, we can now use the prefered methods.

2021-04-14 04:36 UTC, jaydenseric approved these changes
I don’t have the bandwidth right now to go too deep into reviewing this, but the approach looks good to me.

2021-04-14 04:36 UTC, merged

2021-04-14 04:38 UTC, jaydenseric commented
It would be absurd, but I wonder what would happen if you constructed a new `fs-capacitor` Read stream after the process `exit` event has been fired, say, within an `exit` event handler.

2021-04-14 05:51 UTC, mike-marcacci commented
That's a good question with a pretty straightforward answer actually: nothing 🙃

Node will not schedule another event frame when this event is fired, and so only synchronous code gets executed in these handlers.